### ISSUE TITLE
Add ability to apply a simple filter to the Landsat layer in the Dashboard

### ISSUE THREAD

**Issue by jsolly** [easierdata/web3-geo-dashboard#14]

**Comment by jsolly** [comment]
@marquisvictor Putting this in your up next. Could you think of at least one way to filter the data and add this filter functionality to the Dashboard?

You'll have to research whether this is a Mapbox component or something else.

**Comment by jsolly** [comment]
Let's put this on hold in favor of working on the search component that will allow people to search for an area of interest.

**Comment by matthewnanas** [comment]
Added path/row filter
