### ISSUE TITLE
Make map take up whole <main> container

### ISSUE THREAD

**Issue by jsolly** [easierdata/web3-geo-dashboard#28]
## Context 
Currently, the map looks like this
![image](https://github.com/easierdata/web3-geo-dashboard/assets/9572232/81f7ca82-290c-43c5-9401-3151c8ba5bdf)

## Current Behavior/Workaround
I tried making the Width/height 100%, but this overflowed into the footer
![image](https://github.com/easierdata/web3-geo-dashboard/assets/9572232/a20187bd-0612-4dad-bb84-1390c7df5ab4)

## Ideal behavior
We should maybe use CSS Grid to separate the layout into something like this because we will eventually want charts/widgets on the right and left sides of the map.
```css
  grid-template-areas:
    "header header header"
    "left-charts map right-charts"
    "footer footer footer";
```
@marquisvictor what do you think?

**Comment by marquisvictor** [comment]
@jsolly I agree. I think we should center the map in the viewport. I am not a big fan of grid layouts primarily because of their responsiveness. But we'll def find a way. 

What are the left charts and right charts? can you explain a little bit further.

**Comment by jsolly** [comment]
On second thought. let's put the other widgets and charts on hold. 

For now, let's just center the map in the viewport
