### ISSUE TITLE
Find best way to fetch IPFS and filecoin metadata from the backend

### ISSUE THREAD

**Issue by jsolly** [easierdata/web3-geo-dashboard#5]
## Context 
This issue is closely tied to https://github.com/easierdata/web3-geo-dashboard/issues/2 but focuses on how and where to get the data.

## Things to consider
We will need to decide what we want to store and/or cache locally and what we want to query on-demand.

I think the on-demand queries will be 'on-click' events triggered by clicking on a feature (Landsat Scene) in the map.

I still haven't quite wrapped my head around what Svelte does 'in the browser' and what it does 'on the server'

It shouldn't matter too much, as this is not sensitive data. It's okay if we are doing a lot of things client-side if it makes more sense.

Assigning @matthewnanas as he specifically said he would be interested in working on this piece.

**Comment by matthewnanas** [comment]
After inspecting the CID.contact request that retrieves metadata, I noticed it uses their [API](https://docs.cid.contact/query-and-retrieve/querying-indexer-provider) which gives me reason to believe that deal and protocol information are encoded in the response. I will do more digging to figure out how to turn the response into a more interpretable format.

**Comment by matthewnanas** [comment]
Created a branch that fetches for very high level information

**Comment by jsolly** [comment]
@matthewnanas please link PR and close. Nice work.

**Comment by jsolly** [comment]
This is now in a separate repo
https://github.com/easierdata/easier-dashboard-api
